//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedilabMailer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Novedad
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> FechaPublicacion { get; set; }
        public int IdTemplate { get; set; }
        public string mail { get; set; }
    
        public virtual Template Template { get; set; }
    }
}
